import { watch } from 'node:fs'
import { join } from 'node:path'
import { parseArgs } from 'node:util'
import { $ } from 'bun'
import { Glob } from 'bun'

// The Obsidian plugin id comes from the manifest, NOT from package.json: the
// package/repo name is usually prefixed (`obsidian-foo`) while Obsidian keys
// plugins - and their vault folder - by the manifest id (`foo`). Using the
// package name here installs a duplicate folder alongside the real install.
const manifestJson = (await Bun.file('manifest.json').json()) as { id: string }

// Exported constants for testing
export const SRC = 'src'
export const DIST = '.'
export const ASSETS_SRC = `${SRC}/assets`
export const STYLES_SRC = `${SRC}/styles.src.css`
export const STYLES_OUT = 'styles.css'
export const PLUGIN_ID = manifestJson.id
export const BANNER = `/*
THIS IS A GENERATED/BUNDLED FILE BY BUN.
If you want to view the source, please visit the github repository of this plugin.
*/
`

export const EXTERNAL_MODULES = [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr'
]

const { values } = parseArgs({
    args: Bun.argv,
    options: {
        prod: {
            type: 'boolean',
            default: false
        }
    },
    strict: true,
    allowPositionals: true
})
const isProd = values.prod

async function buildStyles(): Promise<void> {
    console.log('Building Tailwind CSS...')
    try {
        const minifyFlag = isProd ? '--minify' : ''
        await $`node ./node_modules/@tailwindcss/cli/dist/index.mjs -i ${STYLES_SRC} -o ${STYLES_OUT} ${minifyFlag}`.quiet()
        console.log('CSS build succeeded.')
    } catch (error) {
        console.error('CSS build failed:', error)
        if (isProd) {
            throw error
        }
    }
}

async function buildJs(): Promise<void> {
    console.log(`Building plugin in ${isProd ? 'production' : 'development'} mode...`)
    const { success, logs } = await Bun.build({
        banner: BANNER,
        entrypoints: [`${SRC}/main.ts`],
        outdir: DIST,
        external: EXTERNAL_MODULES,
        format: 'cjs',
        target: 'node',
        minify: isProd,
        sourcemap: isProd ? false : 'inline',
        throw: isProd
    })
    if (success) {
        console.log('JS build succeeded.')
    } else {
        console.error('JS build failed.')
        console.error(logs)
    }
}

async function copyAssets(): Promise<void> {
    console.log('Copying assets...')
    const glob = new Glob('**/*')

    for await (const file of glob.scan({ cwd: ASSETS_SRC, onlyFiles: true })) {
        const src = join(ASSETS_SRC, file)
        const dest = join(DIST, file)
        await Bun.write(dest, Bun.file(src))
        console.log(`  ✓ ${file}`)
    }
}

async function build(): Promise<void> {
    await Promise.all([buildJs(), buildStyles(), copyAssets()])
}

// Only run if executed directly
if (import.meta.main) {
    await build()

    if (!isProd) {
        watch(`${SRC}`, { recursive: true }, async (event, path) => {
            console.log(`Detected ${event} in ${SRC}/${path}`)
            await build()
        })
    }
}
